### ISSUE TITLE
deb9-dev-machine on Chrome OS with Deb10

### ISSUE THREAD

**Issue by sam-splat** [andrewbrg/deb-dev-machine#2]
Hi there,

Is there any large gotcha that would prevent this super installer from working on the updated Crostini Container that’s now using Debian 10?

Thank you and thank you for the tool in the first place, it’s a massive time saver.

**Comment by andrewbrg** [comment]
Hi, I tried it on 10 cause I moved to it too, there were some parts which
don't work well but I just pushed a fix for it (untested) and renamed the
repo to deb-dev-machine

Let me know how it goes :)

**Comment by sam-splat** [comment]
That’s super, thank you. If I come across anything I will certainly post an issue or if capable do the fix. :)

This has been incredibly useful so I’m glad you built it. 

Cheers.

> Hi, I tried it on 10 cause I moved to it too, there were some parts which don't work well but I just pushed a fix for it (untested) and renamed the repo to deb-dev-machine Let me know how it goes :)
> […](#)

**Comment by andrewbrg** [comment]
Thanks :)
